# -*- coding: utf-8 -*-
"""db_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-tMaw-k7nlh_fKsx12wu8YWBaxzUHfyu
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

import pandas as pd


# =========================================================
# Dataclasses
# =========================================================

@dataclass
class DBSplitResult:
    """
    Result of splitting a population into DB-hit and DB-miss groups.
    """
    db_hit_df: pd.DataFrame
    db_miss_df: pd.DataFrame


# =========================================================
# Main class
# =========================================================

class ExactMatchDB:
    """
    V1 exact-match database helper for MLGA.

    Responsibilities
    ----------------
    1. Load/save DB from CSV
    2. Build exact-match keys from design variables
    3. Split population into DB-hit / DB-miss
    4. Append newly evaluated physics results into DB
    5. Remove duplicates by exact key

    Notes
    -----
    - V1 only supports exact match on design variables.
    - Fuzzy search / nearest-neighbor lookup can be added in V2.
    """

    DEFAULT_KEY_COLS = ["bs0", "hs2", "steeth", "hr2", "rteeth", "turn"]

    def __init__(
        self,
        db_df: Optional[pd.DataFrame] = None,
        key_cols: Optional[List[str]] = None,
        key_col_name: str = "design_key",
        float_precision: int = 8,
    ) -> None:
        self.key_cols = key_cols or self.DEFAULT_KEY_COLS
        self.key_col_name = key_col_name
        self.float_precision = int(float_precision)

        if db_df is None:
            self.db_df = pd.DataFrame(columns=self.key_cols + [self.key_col_name])
        else:
            self.db_df = self._ensure_key(self._validate_dataframe(db_df.copy()))

    # =====================================================
    # Load / Save
    # =====================================================

    @classmethod
    def from_csv(
        cls,
        csv_path: str | Path,
        key_cols: Optional[List[str]] = None,
        key_col_name: str = "design_key",
        float_precision: int = 8,
    ) -> "ExactMatchDB":
        """
        Load DB from CSV. If the file does not exist, initialize an empty DB.
        """
        csv_path = Path(csv_path)

        if csv_path.exists():
            db_df = pd.read_csv(csv_path)
        else:
            key_cols = key_cols or cls.DEFAULT_KEY_COLS
            db_df = pd.DataFrame(columns=key_cols)

        return cls(
            db_df=db_df,
            key_cols=key_cols,
            key_col_name=key_col_name,
            float_precision=float_precision,
        )

    def to_csv(self, csv_path: str | Path, index: bool = False) -> None:
        """
        Save current DB to CSV.
        """
        csv_path = Path(csv_path)
        csv_path.parent.mkdir(parents=True, exist_ok=True)
        self.db_df.to_csv(csv_path, index=index)

    # =====================================================
    # Validation / key creation
    # =====================================================

    def _validate_dataframe(self, df: pd.DataFrame) -> pd.DataFrame:
        # Remove duplicated column names and keep only the first occurrence
        if df.columns.duplicated().any():
            df = df.loc[:, ~df.columns.duplicated()].copy()

        missing = [c for c in self.key_cols if c not in df.columns]
        if missing:
            raise ValueError(f"Missing key columns: {missing}")

        # Ensure each key column is a single Series rather than a DataFrame
        for col in self.key_cols:
            col_obj = df[col]
            if isinstance(col_obj, pd.DataFrame):
                col_obj = col_obj.iloc[:, 0]
            df[col] = pd.to_numeric(col_obj, errors="coerce")

        if df[self.key_cols].isna().any().any():
            bad_cols = df[self.key_cols].columns[df[self.key_cols].isna().any()].tolist()
            raise ValueError(f"NaN detected in key columns after numeric conversion: {bad_cols}")

        return df

    def _format_value(self, col: str, val: float) -> str:
        """
        Convert numeric value into stable string form for exact-match keys.
        """
        if col == "turn":
            return str(int(round(val)))
        return f"{float(val):.{self.float_precision}f}"

    def build_key_series(self, df: pd.DataFrame) -> pd.Series:
        """
        Build exact-match keys from key columns.
        """
        df = self._validate_dataframe(df.copy())

        # Critical fix: if the dataframe is empty, return an empty Series directly
        if len(df) == 0:
            return pd.Series(index=df.index, dtype="object", name=self.key_col_name)

        key_df = pd.DataFrame(index=df.index)

        for col in self.key_cols:
            series = df[col]
            if isinstance(series, pd.DataFrame):
                series = series.iloc[:, 0]

            key_df[col] = series.map(lambda x, c=col: self._format_value(c, x))

        key_series = key_df.astype(str).agg("|".join, axis=1)
        key_series.name = self.key_col_name
        return key_series

    def _ensure_key(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Ensure key column exists and is up to date.
        """
        df = self._validate_dataframe(df.copy())

        if len(df) == 0:
            df[self.key_col_name] = pd.Series(index=df.index, dtype="object")
            return df

        df[self.key_col_name] = self.build_key_series(df)
        return df

    # =====================================================
    # Lookup / split
    # =====================================================

    def split_hit_miss(self, population_df: pd.DataFrame) -> DBSplitResult:
        """
        Split a population into DB-hit and DB-miss.

        Returns
        -------
        db_hit_df:
            Population rows enriched with true DB values where exact key exists.
        db_miss_df:
            Population rows not found in DB.
        """
        population_df = self._ensure_key(population_df.copy())
        db_df = self._ensure_key(self.db_df.copy())

        # Keep one row per key in DB
        db_unique = db_df.drop_duplicates(subset=[self.key_col_name], keep="last").copy()

        hit_mask = population_df[self.key_col_name].isin(db_unique[self.key_col_name])

        pop_hit = population_df.loc[hit_mask].copy()
        pop_miss = population_df.loc[~hit_mask].copy()

        if len(pop_hit) > 0:
            merged_hit = pop_hit.merge(
                db_unique,
                on=self.key_col_name,
                how="left",
                suffixes=("_pop", ""),
            )

            # Keep original population design variables in canonical columns
            for col in self.key_cols:
                pop_col = f"{col}_pop"
                if pop_col in merged_hit.columns:
                    merged_hit[col] = merged_hit[pop_col]

            # Remove temp population duplicate columns
            temp_cols = [f"{col}_pop" for col in self.key_cols if f"{col}_pop" in merged_hit.columns]
            if temp_cols:
                merged_hit.drop(columns=temp_cols, inplace=True)

            # Mark metadata
            merged_hit["db_hit"] = True
            merged_hit["selected_for_physics"] = False
            merged_hit["selection_type"] = None

            # If true_score exists in DB, use it as final fitness
            if "true_score" in merged_hit.columns:
                merged_hit["final_fitness"] = merged_hit["true_score"]

            merged_hit["fitness_source"] = "db"
            db_hit_df = merged_hit.copy()
        else:
            db_hit_df = pop_hit.copy()
            db_hit_df["db_hit"] = True
            db_hit_df["selected_for_physics"] = False
            db_hit_df["selection_type"] = None
            db_hit_df["fitness_source"] = "db"

        if len(pop_miss) > 0:
            pop_miss["db_hit"] = False
        else:
            pop_miss["db_hit"] = False

        return DBSplitResult(
            db_hit_df=db_hit_df,
            db_miss_df=pop_miss,
        )

    # =====================================================
    # Append / deduplicate
    # =====================================================

    def append_results(
        self,
        evaluated_df: pd.DataFrame,
        deduplicate: bool = True,
        keep: str = "last",
    ) -> None:
        """
        Append newly evaluated results into DB.

        Parameters
        ----------
        evaluated_df:
            DataFrame containing at least key columns and true evaluation results.
        deduplicate:
            Whether to remove duplicate keys after append.
        keep:
            Which duplicate to keep: 'first' or 'last'
        """
        if evaluated_df is None or len(evaluated_df) == 0:
            return

        evaluated_df = self._ensure_key(evaluated_df.copy())

        if len(self.db_df) == 0:
            self.db_df = evaluated_df.copy().reset_index(drop=True)
        else:
            self.db_df = pd.concat([self.db_df, evaluated_df], axis=0, ignore_index=True)

        if deduplicate:
            self.db_df = self.db_df.drop_duplicates(
                subset=[self.key_col_name],
                keep=keep,
            ).reset_index(drop=True)

    def deduplicate(self, keep: str = "last") -> None:
        """
        Deduplicate DB by exact design key.
        """
        if len(self.db_df) == 0:
            return

        self.db_df = self._ensure_key(self.db_df.copy())
        self.db_df = self.db_df.drop_duplicates(
            subset=[self.key_col_name],
            keep=keep,
        ).reset_index(drop=True)

    # =====================================================
    # Utilities
    # =====================================================

    def get_db(self) -> pd.DataFrame:
        """
        Return a copy of current DB.
        """
        return self.db_df.copy()

    def __len__(self) -> int:
        return len(self.db_df)
