# -*- coding: utf-8 -*-
"""evaluator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWKo692KB_pbKJTCIDFMOONlKsnq7T5Z
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Dict, Any, Optional, List

import numpy as np
import pandas as pd


# =========================================================
# Basic helpers
# =========================================================

def cosd(x_deg: float) -> float:
    return float(np.cos(np.deg2rad(x_deg)))


def atand(x: float) -> float:
    return float(np.rad2deg(np.arctan(x)))


def safe_tansida(Im, Iw, X1, X2, V1):
    x = (Iw * (X1 + X2) / V1)
    inside = 1 - x**2
    if inside <= 0 or not np.isfinite(inside) or not np.isfinite(Iw):
        return 0.0
    tans = ((Im / Iw) + x) / np.sqrt(inside)
    if not np.isrealobj(tans) or not np.isfinite(tans):
        return 0.0
    return float(np.real(tans))


# =========================================================
# B-H curve data
# =========================================================

CS350H = np.array([
    0, 10, 16.7, 22.3, 26.6, 30.3, 33.4, 36.1, 38.6, 41, 43.5, 46, 48.6,
    51.4, 54.4, 57.6, 61.3, 65.2, 69.6, 74.5, 80.2, 87.1, 95.5, 106, 118,
    132, 151, 179, 226, 312, 489, 914, 1590, 2440, 3540, 5000, 5030, 6970,
    9630, 10000, 13300, 18700, 29300, 80000
], dtype=float)

CS350T = np.array([
    0, 0.007, 0.05, 0.101, 0.151, 0.202, 0.252, 0.302, 0.353, 0.403, 0.454,
    0.504, 0.554, 0.605, 0.655, 0.705, 0.756, 0.806, 0.856, 0.907, 0.957,
    1.008, 1.058, 1.108, 1.159, 1.209, 1.26, 1.31, 1.36, 1.411, 1.461,
    1.512, 1.564, 1.615, 1.667, 1.718, 1.719, 1.767, 1.815, 1.8216,
    1.878, 1.923, 1.987, 2.101
], dtype=float)


def bh_H_from_B(B: float) -> float:
    """
    Interpolate H from B using CS350 B-H curve.

    Parameters
    ----------
    B : float
        Flux density (Tesla)

    Returns
    -------
    float
        Magnetic field intensity H
    """
    if not np.isfinite(B):
        return np.nan

    # B should normally be non-negative in this workflow
    if B < 0:
        B = abs(B)

    # clamp to curve range
    B_clamped = np.clip(B, CS350T[0], CS350T[-1])

    H = np.interp(B_clamped, CS350T, CS350H)
    return float(H)

# =========================================================
# Score reconstruction
# =========================================================

def calculate_true_score(
    eff: float,
    Tstp: float,
    Tmscore: float,
    Ilimite: float,
    pf: float,
) -> float:
    """
    Reconstruct final score using the same MATLAB-style rule.
    Lower is better because final score = -Ans.
    """
    vals = [eff, Tstp, Tmscore, Ilimite, pf]
    if any(pd.isna(x) for x in vals):
        return 0.0

    if Ilimite > 7 or pf >= 1 or pf < 0.75:
        return 0.0
    elif eff < 0.895:
        return -(eff / 0.895)
    else:
        effsc = eff / 0.905
        tstpsc = Tstp / 2.75
        tmsc = Tmscore / 5.25
        return -((effsc + tstpsc + tmsc) - 0.04)


# =========================================================
# Machine config
# =========================================================

@dataclass
class MachineConfig:
    pole: float
    a: float
    Sslot: float
    Rslot: float
    SOD: float
    SID: float
    hs0: float
    hs1: float
    filled: float
    V1: float
    f: float
    kw: float
    length: float
    gap: float
    br01: float
    br1: float
    Ptarget: float = 3100.0
    step: float = 0.01
    max_iter: int = 200000


# =========================================================
# Phase 1: equivalent parameters
# =========================================================

def calc_equiv_params_clean(v: dict):
    """
    計算固定參數（到 I11 為止），並回傳等效電路與損失/磁化參數。
    保證固定 schema：
      ok: bool
      reason: str
      (其餘欄位失敗則為 np.nan)
    """

    out = {
        "ok": False,
        "reason": "",

        # input echo
        "pole": v.get("pole", np.nan),
        "a": v.get("a", np.nan),
        "Sslot": v.get("Sslot", np.nan),
        "Rslot": v.get("Rslot", np.nan),
        "SOD": v.get("SOD", np.nan),
        "SID": v.get("SID", np.nan),
        "hs0": v.get("hs0", np.nan),
        "hs1": v.get("hs1", np.nan),
        "hs2": v.get("hs2", np.nan),
        "bs0": v.get("bs0", np.nan),
        "steeth": v.get("steeth", np.nan),
        "hr2": v.get("hr2", np.nan),
        "rteeth": v.get("rteeth", np.nan),
        "turn": v.get("turn", np.nan),
        "filled": v.get("filled", np.nan),
        "V1": v.get("V1", np.nan),
        "f": v.get("f", np.nan),
        "kw": v.get("kw", np.nan),
        "length": v.get("length", np.nan),
        "gap": v.get("gap", np.nan),
        "br01": v.get("br01", np.nan),
        "br1": v.get("br1", np.nan),

        # computed essentials
        "area": np.nan,
        "C": np.nan,
        "C0": np.nan,
        "Lave": np.nan,
        "R1": np.nan,
        "R2": np.nan,
        "s": np.nan,
        "X1": np.nan,
        "X2": np.nan,
        "Im": np.nan,
        "Xm": np.nan,
        "Rc": np.nan,
        "Coreloss": np.nan,
        "I11": np.nan + 1j*np.nan,

        # optional debug
        "slotu": np.nan,
        "slotd": np.nan,
        "Syoke": np.nan,
        "rslotu": np.nan,
        "rslotd": np.nan,
        "Ryoke": np.nan,
        "mf": np.nan,
        "Bt1": np.nan, "By1": np.nan, "Bt2": np.nan, "By2": np.nan,
        "Ht1": np.nan, "Hy1": np.nan, "Ht2": np.nan, "Hy2": np.nan,
        "att": np.nan,
    }

    try:
        pole   = float(v["pole"])
        a      = float(v["a"])
        Sslot  = float(v["Sslot"])
        Rslot  = float(v["Rslot"])
        SOD    = float(v["SOD"])
        SID    = float(v["SID"])
        hs0    = float(v["hs0"])
        hs1    = float(v["hs1"])
        hs2    = float(v["hs2"])
        bs0    = float(v["bs0"])
        steeth = float(v["steeth"])
        hr2    = float(v["hr2"])
        rteeth = float(v["rteeth"])
        turn   = float(v["turn"])
        filled = float(v["filled"])
        V1     = float(v["V1"])
        f      = float(v["f"])
        kw     = float(v["kw"])
        length = float(v["length"])
        gap    = float(v["gap"])
        br01   = float(v["br01"])
        br1    = float(v["br1"])
    except KeyError as e:
        out["reason"] = f"missing_key_{str(e)}"
        return out
    except Exception:
        out["reason"] = "bad_input_cast"
        return out

    if pole <= 0 or a <= 0 or Sslot <= 0 or Rslot <= 0:
        out["reason"] = "bad_basic_counts"
        return out
    if kw <= 0 or f <= 0 or V1 <= 0 or length <= 0:
        out["reason"] = "bad_basic_elec"
        return out
    if filled <= 0 or filled > 1:
        out["reason"] = "bad_filled"
        return out
    if turn <= 0:
        out["reason"] = "bad_turn"
        return out

    try:
        Syoke = (SOD - (SID + 2*(hs0+hs1+hs2 + ((((SID + 2*(hs0+hs1+hs2))*np.pi/Sslot) - steeth)/2))))/2
        slotu = ((SID + 2*(hs0+hs1+hs2))*np.pi/Sslot) - steeth
        slotd = ((SID + 2*(hs0+hs1))*np.pi/Sslot) - steeth
        slotc = (slotu**2)/4 * np.pi/2
        area  = ((slotu + slotd)*hs2/2) + slotc
    except Exception:
        out["reason"] = "stator_geometry_fail"
        return out

    if not np.isfinite(area) or area <= 0:
        out["reason"] = "bad_area"
        out.update({"area": area, "slotu": slotu, "slotd": slotd, "Syoke": Syoke})
        return out

    C  = turn * 2
    C0 = C * (Sslot / pole)
    if not np.isfinite(C0) or C0 <= 0:
        out["reason"] = "bad_C0"
        return out

    mf = V1 / (2.22 * f * kw * C0)

    Lew  = 1.55*np.pi*(7/Sslot)*(SID + 2*hs2)
    Lave = 2 * (length + Lew)

    R1 = 1.7e-8 * (C0 * Lave * 1e-3) * turn / (area * filled * 1e-6) / 2.0

    if not np.isfinite(R1) or R1 <= 0:
        out["reason"] = "bad_R1"
        out.update({"area": area, "C0": C0, "Lave": Lave, "R1": R1})
        return out

    rslotu = ((SID - 2*(hr2 + br01 + gap + br1))*np.pi/Rslot) - rteeth
    rslotd = ((SID - 2*(br01 + gap + br1))*np.pi/Rslot) - rteeth
    Ryoke  = (145 - (rslotu + rslotd) - 2*hr2 - 70)/2

    Asr  = (rslotu**2)/4*np.pi/2 + (rslotd**2)/4*np.pi/2 + ((rslotu+rslotd)*hr2/2)
    Abar = Asr * cosd(5.67592)

    Dring = (134 + 145)/2
    KR = (pole/2) * (1 - (134/Dring)) * ((1 + (134/Dring)**pole) / (1 - (134/Dring)**pole))

    Rbar  = KR * 2.82e-11 * (length/cosd(5.67592)) / (Abar * 1e-6)
    Aring = 22 * 12
    Rring = KR * 2.82e-8 * ((np.pi*Dring*1e-3) / (Aring*1e-6))

    aratio = (Sslot/Rslot) * (C*kw/a)
    R2 = 1.2 * ((Rslot*Rbar + ((Rslot/(pole*np.pi))**2 * Rring))/3) * (aratio**2)

    s = 0.0365*R2 - 0.0042

    if (not np.isfinite(R2)) or R2 <= 0:
        out["reason"] = "bad_R2"
        out.update({"R2": R2})
        return out
    if (not np.isfinite(s)) or s <= 0:
        out["reason"] = "bad_slip"
        out.update({"R2": R2, "s": s})
        return out

    Bt1 = mf / (steeth / ((145*np.pi)/Sslot)) / (2/pole) / 145 / length / 1e-6
    By1 = mf / (2*Syoke*length*1e-6)
    Bt2 = mf / (Rslot*rteeth*length*1e-6/9)
    By2 = mf / (2*Ryoke*length*1e-6)

    Ht1 = bh_H_from_B(Bt1)
    Hy1 = bh_H_from_B(By1)
    Ht2 = bh_H_from_B(Bt2)
    Hy2 = bh_H_from_B(By2)

    At1 = Ht1*(hs0+hs1+hs2+(slotu/2))*1e-3
    Ay1 = Hy1*(np.pi*0.22/12)
    At2 = Ht2*(br01+hr2+((rslotu+rslotd)/2))*1e-3
    Ay2 = Hy2*(np.pi*(145-(2*gap)-2*(br01+hr2+((rslotu+rslotd)/2)))/12)*1e-3

    Bg  = Bt1 * (steeth / ((145*np.pi)/Sslot))
    Atg = 0.8*(1e6)*Bg*1.3*gap*1e-3

    att = At1 + Ay1 + At2 + Ay2 + Atg

    Wt1 = steeth*hs2*length*Sslot*1e-9
    Wy1 = (((220/2)**2*np.pi) - (((220-(2*Syoke))/2)**2*np.pi))*length*1e-9
    Wt2 = rteeth*hr2*length*Rslot*1e-9
    Wy2 = ((((145-(2*hr2+rslotd+rslotu))/2)**2*np.pi) - (21**2*np.pi))*1e-9

    Pt1 = ((138.581*60*Bt1**2) + (0.428733*(60*Bt1)**2)) * Wt1 * 2.23
    Py1 = ((138.581*60*By1**2) + (0.428733*(60*By1)**2)) * Wy1 * 2.23
    Pt2 = ((138.581*(60*s)*Bt2**2) + (0.428733*(60*s*Bt2)**2)) * Wt2 * 2.23
    Py2 = ((138.581*(60*s)*By2**2) + (0.428733*(60*s*By2)**2)) * Wy2 * 2.23

    Coreloss = Pt1 + Py1 + Pt2 + Py2

    if not np.isfinite(Coreloss) or Coreloss <= 0:
        out["reason"] = "bad_coreloss"
        return out

    Im = 1.16 * pole * att / (C0 * kw)
    if not np.isfinite(Im) or Im <= 0:
        out["reason"] = "bad_Im"
        return out

    Xm = V1 / Im
    Rc = (0.97*V1)**2 / (Coreloss/3)

    lamdas1 = (20/3/3) * (0.905/kw**2) * (
        (hs0/bs0)
        + (2*hs1/(bs0+slotd))
        + (2*(hs2+(slotu/2)+hs0+hs1)/(3*(slotu+slotd)))
    )

    kx = 4*f*length*1e-3*3*pole*(kw*3*C/a)**2*1e-7

    Xs1 = kx * lamdas1
    lamdae1 = 4*(8+22)/length
    Xe1 = kx * lamdae1
    lamdac1 = (5/6) * Xm * (pole/Sslot)**2
    X1 = Xs1 + Xe1 + lamdac1

    lamdas2 = (20*pole/3/Rslot) * (
        (br01/br1)
        + ((rslotu/2)/(br1+rslotd))
        + (2*hr2/(3*(rslotu+rslotd)))
    )

    Xs2 = kx * lamdas2

    hcr = (145+hs0+hs1+(hs2/2)) - (145-br01-(hr2/2))
    lamdae2 = (5.8/length)*(np.pi*145*hcr)/pole/(1.7*22+1.2*12+1.4*hcr)
    Xe2 = kx * lamdae2
    lamdac2 = (5/6) * Xm * (pole/Rslot)**2
    Xsk = (220/(12*Im)) * (np.pi*1.2*pole/Rslot)**2

    X2 = Xs2 + Xe2 + lamdac2 + Xsk

    if not np.isfinite(X1) or not np.isfinite(X2):
        out["reason"] = "bad_X"
        return out

    Z1 = R1 + 1j*X1
    Z2 = R2/s + 1j*X2
    Ztm = (1j*Xm * Rc) / (1j*Xm + Rc)
    Zf  = (Ztm * Z2) / (Ztm + Z2)
    Zt  = Z1 + Zf
    I11 = V1 / Zt

    if not (np.isfinite(np.real(I11)) and np.isfinite(np.imag(I11))):
        out["reason"] = "bad_I11"
        return out

    out.update({
        "ok": True,
        "reason": "ok",

        "Syoke": float(Syoke),
        "slotu": float(slotu),
        "slotd": float(slotd),
        "area": float(area),
        "C": float(C),
        "C0": float(C0),
        "mf": float(mf),
        "Lave": float(Lave),

        "R1": float(R1),
        "rslotu": float(rslotu),
        "rslotd": float(rslotd),
        "Ryoke": float(Ryoke),
        "R2": float(R2),
        "s": float(s),

        "Bt1": float(Bt1), "By1": float(By1), "Bt2": float(Bt2), "By2": float(By2),
        "Ht1": float(Ht1), "Hy1": float(Hy1), "Ht2": float(Ht2), "Hy2": float(Hy2),
        "att": float(att),

        "Coreloss": float(Coreloss),
        "Im": float(Im),
        "Xm": float(Xm),
        "Rc": float(Rc),
        "X1": float(X1),
        "X2": float(X2),
        "I11": I11,
    })
    return out


# =========================================================
# Phase 2: solve at target power
# =========================================================

def solve_at_target_power_core(
    V1, I11, Im, R1, R2, X1, X2, s, Coreloss, f, pole,
    Ptarget=3100.0,
    step=0.01,
    max_iter=200000,
):
    out = {
        "ok": False,
        "reason": "",
        "I1": np.nan, "Iw": np.nan, "tansida": np.nan, "pf": np.nan,
        "Pin": np.nan, "loss": np.nan, "Pout": np.nan, "eff": np.nan,
        "Ist": np.nan, "Tstp": np.nan, "Tmscore": np.nan, "Ilimite": np.nan,
        "Pcu_stator": np.nan, "Pcu_rotor": np.nan, "Pcore": float(Coreloss),
        "Ploss_total": np.nan,
    }

    if not np.isfinite(s) or s <= 0:
        out["reason"] = "bad_slip"
        return out
    if not np.isfinite(Im) or Im <= 0:
        out["reason"] = "bad_Im"
        return out
    if not np.isfinite(R1) or R1 <= 0 or (not np.isfinite(R2)) or R2 <= 0:
        out["reason"] = "bad_R"
        return out
    if not np.isfinite(X1) or not np.isfinite(X2):
        out["reason"] = "bad_X"
        return out
    if not np.isfinite(V1) or V1 <= 0:
        out["reason"] = "bad_V1"
        return out
    if (not np.isfinite(Coreloss)) or Coreloss < 0:
        out["reason"] = "bad_coreloss"
        return out

    I1 = abs(I11) * np.sqrt(3)
    I2 = V1 / np.sqrt((R2/s)**2 + X2**2)
    R2loss = np.sqrt(3) * (I2**2) * R2 * 1.5

    def calc_once(I1_local):
        if not np.isfinite(I1_local) or I1_local <= 0:
            return (np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan)

        diff = I1_local**2 - Im**2
        if diff <= 0:
            Iw = 0.0
            return (Iw, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan)

        Iw = 1.05*np.sqrt(diff)
        x = (Iw*(X1+X2)/V1)
        inside = 1 - x**2
        if (inside <= 0) or (not np.isfinite(inside)) or (Iw == 0):
            return (Iw, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan)

        tansida = ((Im/Iw) + x) / np.sqrt(inside)
        if (not np.isrealobj(tansida)) or (not np.isfinite(tansida)):
            tansida = 0.0

        pf = float(np.cos(np.arctan(float(np.real(tansida)))))
        if (not np.isfinite(pf)) or (pf <= 0) or (pf > 1):
            return (Iw, float(np.real(tansida)), np.nan, np.nan, np.nan, np.nan, np.nan)

        R1loss = np.sqrt(3) * (I1_local**2) * R1
        loss = Coreloss + R1loss + R2loss
        Pin  = np.sqrt(3) * V1 * I1_local * pf
        Pout = Pin - loss - (Ptarget*0.02) - (Ptarget*0.01)

        return (Iw, float(np.real(tansida)), float(pf), float(R1loss), float(loss), float(Pin), float(Pout))

    Iw, tansida, pf, R1loss, loss, Pin, Pout = calc_once(I1)

    if not np.isfinite(Pout):
        out.update({
            "I1": float(I1) if np.isfinite(I1) else np.nan,
            "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
            "tansida": tansida,
            "pf": pf,
            "Pcu_rotor": float(R2loss),
            "reason": "invalid_domain_initial",
        })
        return out

    it = 0
    while Pout <= Ptarget and it < max_iter:
        I1 += step
        Iw, tansida, pf, R1loss, loss, Pin, Pout = calc_once(I1)
        it += 1

        if not np.isfinite(Pout):
            out.update({
                "I1": float(I1),
                "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
                "tansida": tansida,
                "pf": pf,
                "Pcu_rotor": float(R2loss),
                "reason": "invalid_domain_push",
            })
            return out

        if np.isfinite(loss) and (loss > Ptarget):
            out.update({
                "ok": False,
                "reason": "loss_gt_target",
                "I1": float(I1),
                "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
                "tansida": tansida,
                "pf": pf,
                "Pin": float(Pin) if np.isfinite(Pin) else np.nan,
                "loss": float(loss) if np.isfinite(loss) else np.nan,
                "Pout": float(Pout) if np.isfinite(Pout) else np.nan,
                "Pcu_stator": float(R1loss) if np.isfinite(R1loss) else np.nan,
                "Pcu_rotor": float(R2loss),
                "Pcore": float(Coreloss),
                "Ploss_total": float(loss) if np.isfinite(loss) else np.nan,
            })
            return out

    if it >= max_iter:
        out.update({
            "I1": float(I1),
            "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
            "tansida": tansida,
            "pf": pf,
            "Pin": float(Pin) if np.isfinite(Pin) else np.nan,
            "loss": float(loss) if np.isfinite(loss) else np.nan,
            "Pout": float(Pout) if np.isfinite(Pout) else np.nan,
            "Pcu_stator": float(R1loss) if np.isfinite(R1loss) else np.nan,
            "Pcu_rotor": float(R2loss),
            "reason": "max_iter_push",
        })
        return out

    it = 0
    while Pout >= Ptarget and it < max_iter:
        I1 -= step
        Iw, tansida, pf, R1loss, loss, Pin, Pout = calc_once(I1)
        it += 1

        if not np.isfinite(Pout):
            out.update({
                "I1": float(I1),
                "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
                "tansida": tansida,
                "pf": pf,
                "Pcu_rotor": float(R2loss),
                "reason": "invalid_domain_pull",
            })
            return out

        if np.isfinite(loss) and (loss > Ptarget):
            out.update({
                "ok": False,
                "reason": "loss_gt_target",
                "I1": float(I1),
                "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
                "tansida": tansida,
                "pf": pf,
                "Pin": float(Pin) if np.isfinite(Pin) else np.nan,
                "loss": float(loss) if np.isfinite(loss) else np.nan,
                "Pout": float(Pout) if np.isfinite(Pout) else np.nan,
                "Pcu_stator": float(R1loss) if np.isfinite(R1loss) else np.nan,
                "Pcu_rotor": float(R2loss),
                "Pcore": float(Coreloss),
                "Ploss_total": float(loss) if np.isfinite(loss) else np.nan,
            })
            return out

    if it >= max_iter:
        out.update({
            "I1": float(I1),
            "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
            "tansida": tansida,
            "pf": pf,
            "Pin": float(Pin) if np.isfinite(Pin) else np.nan,
            "loss": float(loss) if np.isfinite(loss) else np.nan,
            "Pout": float(Pout) if np.isfinite(Pout) else np.nan,
            "Pcu_stator": float(R1loss) if np.isfinite(R1loss) else np.nan,
            "Pcu_rotor": float(R2loss),
            "reason": "max_iter_pull",
        })
        return out

    eff = Pout / Pin if (np.isfinite(Pout) and np.isfinite(Pin) and Pin != 0) else np.nan

    w = (1200*(1 - s))*np.pi/30
    Ist = V1 / np.sqrt((R1 + R2)**2 + (X1 + X2)**2)
    Tst = ((3 * Ist**2 * R2) / (4*np.pi*f/pole))
    Tn  = 9.8*973*3.1/(1200*(1 - s))
    Tm  = (3/w) * (0.5*V1**2/(R1 + np.sqrt(R1**2 + (X1+X2)**2)))

    invalid_vals = {
        "Pin": Pin,
        "Pout": Pout,
        "loss": loss,
        "eff": eff,
        "pf": pf,
        "I1": I1,
    }
    for k, v in invalid_vals.items():
        if (not np.isfinite(v)) or (v < 0):
            out.update({
                "ok": False,
                "reason": f"negative_or_nan_{k}",
                "I1": float(I1) if np.isfinite(I1) else np.nan,
                "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
                "tansida": float(tansida) if np.isfinite(tansida) else np.nan,
                "pf": float(pf) if np.isfinite(pf) else np.nan,
                "Pin": float(Pin) if np.isfinite(Pin) else np.nan,
                "loss": float(loss) if np.isfinite(loss) else np.nan,
                "Pout": float(Pout) if np.isfinite(Pout) else np.nan,
                "Pcu_stator": float(R1loss) if np.isfinite(R1loss) else np.nan,
                "Pcu_rotor": float(R2loss),
                "Pcore": float(Coreloss),
                "Ploss_total": float(loss) if np.isfinite(loss) else np.nan,
            })
            return out

    if Pout > Pin + 1e-9:
        out.update({
            "ok": False,
            "reason": "Pout_gt_Pin",
            "I1": float(I1),
            "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
            "tansida": float(tansida) if np.isfinite(tansida) else np.nan,
            "pf": float(pf),
            "Pin": float(Pin),
            "loss": float(loss),
            "Pout": float(Pout),
            "Pcu_stator": float(R1loss) if np.isfinite(R1loss) else np.nan,
            "Pcu_rotor": float(R2loss),
            "Pcore": float(Coreloss),
            "Ploss_total": float(loss),
        })
        return out

    if (eff <= 0) or (eff >= 1):
        out.update({
            "ok": False,
            "reason": "eff_out_of_range",
            "I1": float(I1),
            "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
            "tansida": float(tansida) if np.isfinite(tansida) else np.nan,
            "pf": float(pf),
            "Pin": float(Pin),
            "loss": float(loss),
            "Pout": float(Pout),
            "Pcu_stator": float(R1loss) if np.isfinite(R1loss) else np.nan,
            "Pcu_rotor": float(R2loss),
            "Pcore": float(Coreloss),
            "Ploss_total": float(loss),
        })
        return out

    if (pf <= 0) or (pf > 1):
        out.update({
            "ok": False,
            "reason": "pf_out_of_range",
            "I1": float(I1),
            "Iw": float(Iw) if np.isfinite(Iw) else np.nan,
            "tansida": float(tansida) if np.isfinite(tansida) else np.nan,
            "pf": float(pf),
            "Pin": float(Pin),
            "loss": float(loss),
            "Pout": float(Pout),
            "Pcu_stator": float(R1loss) if np.isfinite(R1loss) else np.nan,
            "Pcu_rotor": float(R2loss),
            "Pcore": float(Coreloss),
            "Ploss_total": float(loss),
        })
        return out

    out.update({
        "ok": True,
        "reason": "ok",
        "I1": float(I1),
        "Iw": float(Iw),
        "tansida": float(tansida),
        "pf": float(pf),
        "Pin": float(Pin),
        "loss": float(loss),
        "Pout": float(Pout),
        "eff": float(eff),
        "Ist": float(Ist),
        "Tstp": float(Tst/Tn),
        "Tmscore": float(Tm/Tn),
        "Ilimite": float(Ist/I1) if I1 != 0 else np.inf,
        "Pcu_stator": float(R1loss),
        "Pcu_rotor": float(R2loss),
        "Pcore": float(Coreloss),
        "Ploss_total": float(loss),
    })
    return out


# =========================================================
# Main evaluator class
# =========================================================

class PhysicsEvaluator:
    DESIGN_COLS = ["bs0", "hs2", "steeth", "hr2", "rteeth", "turn"]

    def __init__(self, config: MachineConfig):
        self.config = config

    def build_input_dict(self, row: pd.Series | Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(row, pd.Series):
            row = row.to_dict()

        v = asdict(self.config).copy()
        for col in self.DESIGN_COLS:
            v[col] = row[col]
        return v

    def _format_failed_result(
        self,
        v: Dict[str, Any],
        phase1: Dict[str, Any],
        phase2: Optional[Dict[str, Any]],
    ) -> Dict[str, Any]:
        reason = phase1.get("reason", "phase1_fail")
        if phase2 is not None and phase2.get("reason"):
            reason = phase2.get("reason")

        result = {
            # design vars
            "bs0": v["bs0"],
            "hs2": v["hs2"],
            "steeth": v["steeth"],
            "hr2": v["hr2"],
            "rteeth": v["rteeth"],
            "turn": v["turn"],

            # true targets
            "ok_true": 0,
            "reason_true": reason,
            "eff_true": np.nan,
            "Tstp_true": np.nan,
            "Tmscore_true": np.nan,
            "Ilimite_true": np.nan,
            "pf_true": np.nan,
            "Pin_true": np.nan,
            "Pout_true": np.nan,
            "loss_true": np.nan,

            # intermediate physics
            "R1": phase1.get("R1", np.nan),
            "R2": phase1.get("R2", np.nan),
            "s": phase1.get("s", np.nan),
            "X1": phase1.get("X1", np.nan),
            "X2": phase1.get("X2", np.nan),
            "Im": phase1.get("Im", np.nan),
            "Coreloss": phase1.get("Coreloss", np.nan),

            # optional I11 split
            "I11_real": np.nan,
            "I11_imag": np.nan,
            "I11_abs": np.nan,

            # final score / metadata
            "true_score": 0.0,
            "fitness_source": "physics",
            "selected_for_physics": True,
        }

        i11 = phase1.get("I11", np.nan + 1j*np.nan)
        if np.isfinite(np.real(i11)):
            result["I11_real"] = float(np.real(i11))
        if np.isfinite(np.imag(i11)):
            result["I11_imag"] = float(np.imag(i11))
        if np.isfinite(np.abs(i11)):
            result["I11_abs"] = float(np.abs(i11))

        if phase2 is not None:
            result["Pin_true"] = phase2.get("Pin", np.nan)
            result["Pout_true"] = phase2.get("Pout", np.nan)
            result["loss_true"] = phase2.get("loss", np.nan)
            result["pf_true"] = phase2.get("pf", np.nan)

        return result

    def _format_success_or_fail(
        self,
        v: Dict[str, Any],
        phase1: Dict[str, Any],
        phase2: Dict[str, Any],
    ) -> Dict[str, Any]:
        if not phase2.get("ok", False):
            return self._format_failed_result(v, phase1, phase2)

        eff = phase2.get("eff", np.nan)
        tstp = phase2.get("Tstp", np.nan)
        tmscore = phase2.get("Tmscore", np.nan)
        ilimite = phase2.get("Ilimite", np.nan)
        pf = phase2.get("pf", np.nan)
        true_score = calculate_true_score(eff, tstp, tmscore, ilimite, pf)

        i11 = phase1.get("I11", np.nan + 1j*np.nan)

        result = {
            # design vars
            "bs0": v["bs0"],
            "hs2": v["hs2"],
            "steeth": v["steeth"],
            "hr2": v["hr2"],
            "rteeth": v["rteeth"],
            "turn": v["turn"],

            # true targets
            "ok_true": 1,
            "reason_true": "ok",
            "eff_true": eff,
            "Tstp_true": tstp,
            "Tmscore_true": tmscore,
            "Ilimite_true": ilimite,
            "pf_true": pf,
            "Pin_true": phase2.get("Pin", np.nan),
            "Pout_true": phase2.get("Pout", np.nan),
            "loss_true": phase2.get("loss", np.nan),

            # intermediate physics
            "R1": phase1.get("R1", np.nan),
            "R2": phase1.get("R2", np.nan),
            "s": phase1.get("s", np.nan),
            "X1": phase1.get("X1", np.nan),
            "X2": phase1.get("X2", np.nan),
            "Im": phase1.get("Im", np.nan),
            "Coreloss": phase1.get("Coreloss", np.nan),

            # optional I11 split
            "I11_real": float(np.real(i11)) if np.isfinite(np.real(i11)) else np.nan,
            "I11_imag": float(np.imag(i11)) if np.isfinite(np.imag(i11)) else np.nan,
            "I11_abs": float(np.abs(i11)) if np.isfinite(np.abs(i11)) else np.nan,

            # final score / metadata
            "true_score": true_score,
            "fitness_source": "physics",
            "selected_for_physics": True,
        }
        return result

    def evaluate_one(self, row: pd.Series | Dict[str, Any]) -> Dict[str, Any]:
        v = self.build_input_dict(row)

        phase1 = calc_equiv_params_clean(v)
        if not phase1["ok"]:
            return self._format_failed_result(v, phase1, phase2=None)

        phase2 = solve_at_target_power_core(
            V1=v["V1"],
            I11=phase1["I11"],
            Im=phase1["Im"],
            R1=phase1["R1"],
            R2=phase1["R2"],
            X1=phase1["X1"],
            X2=phase1["X2"],
            s=phase1["s"],
            Coreloss=phase1["Coreloss"],
            f=v["f"],
            pole=v["pole"],
            Ptarget=self.config.Ptarget,
            step=self.config.step,
            max_iter=self.config.max_iter,
        )

        return self._format_success_or_fail(v, phase1, phase2)

    def evaluate_population(self, df: pd.DataFrame) -> pd.DataFrame:
        if df is None or len(df) == 0:
            return pd.DataFrame(columns=[
                "bs0", "hs2", "steeth", "hr2", "rteeth", "turn",
                "ok_true", "reason_true",
                "eff_true", "Tstp_true", "Tmscore_true", "Ilimite_true", "pf_true",
                "Pin_true", "Pout_true", "loss_true",
                "R1", "R2", "s", "X1", "X2", "Im", "Coreloss",
                "I11_real", "I11_imag", "I11_abs",
                "true_score", "fitness_source", "selected_for_physics",
            ])

        results = [self.evaluate_one(row) for _, row in df.iterrows()]
        return pd.DataFrame(results)

