# -*- coding: utf-8 -*-
"""ml_gate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJQzViLPsDw1CEAtFq5dxl--mGskBudK
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

import json
import joblib
import numpy as np
import pandas as pd


# =========================================================
# Dataclasses
# =========================================================

@dataclass
class PredictionBundle:
    """
    Full prediction results for all DB-miss candidates.
    """
    features: pd.DataFrame
    p_ok: np.ndarray
    ok_pred: np.ndarray
    target_mean: pd.DataFrame
    target_std: pd.DataFrame
    surrogate_score: np.ndarray
    total_uncertainty: np.ndarray


@dataclass
class SelectionResult:
    """
    Output of ML gate selection.
    """
    prediction_df: pd.DataFrame
    selected_df: pd.DataFrame
    exploit_df: pd.DataFrame
    explore_df: pd.DataFrame
    non_selected_df: pd.DataFrame


# =========================================================
# Main class
# =========================================================

class MLGate:
    """
    V1 ML gate for DB-miss candidates.

    Responsibilities
    ----------------
    1. Load trained classifier/regressors/meta
    2. Predict feasibility and regression targets
    3. Reconstruct surrogate score
    4. Compute uncertainty
    5. Select candidates for expensive physics evaluation

    Notes
    -----
    - This module assumes input candidates are DB-miss only.
    - Exact DB search is handled outside this module.
    - Physics evaluation is handled outside this module.
    """

    DEFAULT_TARGETS = ["eff", "Tstp", "Tmscore", "Ilimite", "pf"]

    def __init__(
        self,
        classifier: Any,
        regressors: Dict[str, List[Any]],
        feature_cols: List[str],
        feasibility_threshold: float = 0.5,
        uncertainty_mode: str = "normalized_sum",
        uncertainty_weights: Optional[Dict[str, float]] = None,
    ) -> None:
        self.classifier = classifier
        self.regressors = regressors
        self.feature_cols = feature_cols
        self.feasibility_threshold = feasibility_threshold
        self.uncertainty_mode = uncertainty_mode
        self.uncertainty_weights = uncertainty_weights or {}

    # =====================================================
    # Constructors / loaders
    # =====================================================

    @classmethod
    def from_model_dir(
        cls,
        model_dir: str | Path,
        feasibility_threshold: float = 0.5,
        uncertainty_mode: str = "normalized_sum",
        uncertainty_weights: Optional[Dict[str, float]] = None,
    ) -> "MLGate":
        """
        Load classifier, regressors, and metadata from model directory.

        Expected files:
        - feas_clf_catboost.joblib
        - reg_eff_seed0.joblib ... reg_eff_seed4.joblib
        - reg_Tstp_seed0.joblib ...
        - reg_Tmscore_seed0.joblib ...
        - reg_Ilimite_seed0.joblib ...
        - reg_pf_seed0.joblib ...
        - mlga_meta.json
        """
        model_dir = Path(model_dir)

        meta_path = model_dir / "mlga_meta.json"
        clf_path = model_dir / "feas_clf_catboost.joblib"

        if not meta_path.exists():
            raise FileNotFoundError(f"Meta file not found: {meta_path}")
        if not clf_path.exists():
            raise FileNotFoundError(f"Classifier file not found: {clf_path}")

        with open(meta_path, "r", encoding="utf-8") as f:
            meta = json.load(f)

        feature_cols = cls._infer_feature_cols_from_meta(meta)
        classifier = joblib.load(clf_path)

        regressors: Dict[str, List[Any]] = {}
        for target in cls.DEFAULT_TARGETS:
            model_paths = sorted(model_dir.glob(f"reg_{target}_seed*.joblib"))
            if len(model_paths) == 0:
                raise FileNotFoundError(
                    f"No regressor models found for target '{target}' in {model_dir}"
                )
            regressors[target] = [joblib.load(p) for p in model_paths]

        return cls(
            classifier=classifier,
            regressors=regressors,
            feature_cols=feature_cols,
            feasibility_threshold=feasibility_threshold,
            uncertainty_mode=uncertainty_mode,
            uncertainty_weights=uncertainty_weights,
        )

    @staticmethod
    def _infer_feature_cols_from_meta(meta: Dict[str, Any]) -> List[str]:
        """
        Try to infer feature columns from meta json.
        Falls back to the known 6 design variables if needed.
        """
        # Try common keys first
        for key in ["feature_cols", "features", "input_features", "design_vars"]:
            if key in meta and isinstance(meta[key], list):
                return meta[key]

        # Fallback to known design variables
        return ["bs0", "hs2", "steeth", "hr2", "rteeth", "turn"]

    # =====================================================
    # Feature preparation
    # =====================================================

    def _prepare_features(self, population: pd.DataFrame | List[dict] | np.ndarray) -> pd.DataFrame:
        """
        Convert input population into feature dataframe with correct column order.
        """
        if isinstance(population, pd.DataFrame):
            df = population.copy()
        elif isinstance(population, list):
            df = pd.DataFrame(population)
        elif isinstance(population, np.ndarray):
            if population.ndim != 2 or population.shape[1] != len(self.feature_cols):
                raise ValueError(
                    f"NumPy input shape must be (n_samples, {len(self.feature_cols)}), "
                    f"got {population.shape}"
                )
            df = pd.DataFrame(population, columns=self.feature_cols)
        else:
            raise TypeError("population must be DataFrame, list[dict], or 2D numpy array")

        missing = [col for col in self.feature_cols if col not in df.columns]
        if missing:
            raise ValueError(f"Missing feature columns: {missing}")

        X = df[self.feature_cols].copy()

        # Ensure numeric
        for col in self.feature_cols:
            X[col] = pd.to_numeric(X[col], errors="coerce")

        if X.isna().any().any():
            bad_cols = X.columns[X.isna().any()].tolist()
            raise ValueError(f"NaN detected in feature columns after numeric conversion: {bad_cols}")

        return X

    # =====================================================
    # Prediction
    # =====================================================

    def predict_feasibility(self, X: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray]:
        """
        Predict feasibility probability and binary feasible label.
        """
        if not hasattr(self.classifier, "predict_proba"):
            raise AttributeError("Classifier does not support predict_proba()")

        p_ok = self.classifier.predict_proba(X)[:, 1]
        ok_pred = (p_ok >= self.feasibility_threshold).astype(int)
        return p_ok, ok_pred

    def predict_targets(self, X: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Predict target means and ensemble stds for each candidate.
        """
        mean_dict: Dict[str, np.ndarray] = {}
        std_dict: Dict[str, np.ndarray] = {}

        for target, models in self.regressors.items():
            if len(models) == 0:
                raise ValueError(f"No models loaded for target: {target}")

            preds = np.column_stack([model.predict(X) for model in models])
            mean_dict[target] = preds.mean(axis=1)
            std_dict[target] = preds.std(axis=1)

        mean_df = pd.DataFrame(mean_dict, index=X.index)
        std_df = pd.DataFrame(std_dict, index=X.index)
        return mean_df, std_df

    # =====================================================
    # Surrogate score
    # =====================================================

    @staticmethod
    def calculate_surrogate_score_row(row: pd.Series) -> float:
        """
        Reconstruct surrogate score using MATLAB-like rule.

        MATLAB logic:
            Tstpscore = Tstp;
            Tmscore   = Tm/Tn;

            if Ilimite>7 || pf>=1 || pf<0.75
                Z=0;
            elseif eff<0.895
                effsc=eff/0.895;
                Tstpsc=0;
                Tmsc=0;
                Ans=((effsc+Tstpsc+Tmsc));
                Z=-Ans;
            else
                effsc=eff/0.905;
                Tstpsc=Tstpscore/2.75;
                Tmsc=Tmscore/5.25;
                Ans=((effsc+Tstpsc+Tmsc))-0.04;
                Z=-Ans;
            end

        Note:
        - Lower score is better because final Z = -Ans
        """
        eff = float(row["eff"])
        tstp = float(row["Tstp"])
        tmscore = float(row["Tmscore"])
        ilimite = float(row["Ilimite"])
        pf = float(row["pf"])

        if ilimite > 7 or pf >= 1 or pf < 0.75:
            z = 0.0
        elif eff < 0.895:
            effsc = eff / 0.895
            ans = effsc
            z = -ans
        else:
            effsc = eff / 0.905
            tstpsc = tstp / 2.75
            tmsc = tmscore / 5.25
            ans = (effsc + tstpsc + tmsc) - 0.04
            z = -ans

        return z

    def calculate_surrogate_score(self, pred_mean: pd.DataFrame) -> np.ndarray:
        """
        Calculate surrogate score for all candidates using predicted target means.
        """
        required = {"eff", "Tstp", "Tmscore", "Ilimite", "pf"}
        missing = required - set(pred_mean.columns)
        if missing:
            raise ValueError(f"Missing required columns for surrogate score: {missing}")

        scores = pred_mean.apply(self.calculate_surrogate_score_row, axis=1)
        return scores.to_numpy()

    # =====================================================
    # Uncertainty
    # =====================================================

    @staticmethod
    def _safe_minmax(series: pd.Series) -> pd.Series:
        smin = series.min()
        smax = series.max()
        if np.isclose(smax, smin):
            return pd.Series(np.zeros(len(series)), index=series.index)
        return (series - smin) / (smax - smin)

    @staticmethod
    def _safe_zscore(series: pd.Series) -> pd.Series:
        mean = series.mean()
        std = series.std()
        if std is None or np.isclose(std, 0.0):
            return pd.Series(np.zeros(len(series)), index=series.index)
        return (series - mean) / std

    def calculate_total_uncertainty(self, pred_std: pd.DataFrame) -> np.ndarray:
        """
        Aggregate uncertainty from per-target ensemble std.

        Modes:
        - raw_sum: direct weighted sum of std
        - minmax_sum: min-max normalize each std then sum
        - normalized_sum: z-score each std then shift to positive-ish by minmax after z
                          (default, more balanced across targets)
        """
        cols = [c for c in self.DEFAULT_TARGETS if c in pred_std.columns]
        if len(cols) == 0:
            raise ValueError("No target std columns found for uncertainty calculation")

        work = pred_std[cols].copy()

        if self.uncertainty_mode == "raw_sum":
            norm_df = work

        elif self.uncertainty_mode == "minmax_sum":
            norm_df = pd.DataFrame(
                {col: self._safe_minmax(work[col]) for col in cols},
                index=work.index,
            )

        elif self.uncertainty_mode == "normalized_sum":
            z_df = pd.DataFrame(
                {col: self._safe_zscore(work[col]) for col in cols},
                index=work.index,
            )
            norm_df = pd.DataFrame(
                {col: self._safe_minmax(z_df[col]) for col in cols},
                index=work.index,
            )

        else:
            raise ValueError(
                "uncertainty_mode must be one of: "
                "['raw_sum', 'minmax_sum', 'normalized_sum']"
            )

        weighted_sum = np.zeros(len(norm_df), dtype=float)
        for col in cols:
            w = float(self.uncertainty_weights.get(col, 1.0))
            weighted_sum += norm_df[col].to_numpy() * w

        return weighted_sum

    # =====================================================
    # Full prediction bundle
    # =====================================================

    def predict_population(self, population: pd.DataFrame | List[dict] | np.ndarray) -> PredictionBundle:
        """
        Predict full ML outputs for all DB-miss candidates.
        """
        X = self._prepare_features(population)
        p_ok, ok_pred = self.predict_feasibility(X)
        target_mean, target_std = self.predict_targets(X)
        surrogate_score = self.calculate_surrogate_score(target_mean)
        total_uncertainty = self.calculate_total_uncertainty(target_std)

        return PredictionBundle(
            features=X,
            p_ok=p_ok,
            ok_pred=ok_pred,
            target_mean=target_mean,
            target_std=target_std,
            surrogate_score=surrogate_score,
            total_uncertainty=total_uncertainty,
        )

    # =====================================================
    # Selection helpers
    # =====================================================

    def _build_prediction_df(self, bundle: PredictionBundle) -> pd.DataFrame:
        """
        Build a flat dataframe for all DB-miss candidates.
        """
        df = bundle.features.copy()

        # Feasibility
        df["p_ok"] = bundle.p_ok
        df["ok_pred"] = bundle.ok_pred

        # Predicted target means
        for col in bundle.target_mean.columns:
            df[f"{col}_pred"] = bundle.target_mean[col].values

        # Predicted target stds
        for col in bundle.target_std.columns:
            df[f"{col}_std"] = bundle.target_std[col].values

        # Scores
        df["surrogate_score"] = bundle.surrogate_score
        df["total_uncertainty"] = bundle.total_uncertainty

        # Default flags for downstream pipeline
        df["selected_for_physics"] = False
        df["selection_type"] = None
        df["fitness_source"] = "ml"

        # Placeholder true columns for downstream merging
        true_cols = [
            "ok_true",
            "eff_true",
            "Tstp_true",
            "Tmscore_true",
            "Ilimite_true",
            "pf_true",
            "true_score",
        ]
        for col in true_cols:
            df[col] = np.nan

        # Final fitness default = surrogate score
        df["final_fitness"] = df["surrogate_score"]

        return df

    # =====================================================
    # Candidate selection
    # =====================================================

    def select_candidates(
        self,
        population: pd.DataFrame | List[dict] | np.ndarray,
        n_exploit: int = 75,
        n_explore: int = 75,
        feasibility_filter: bool = False,
        min_p_ok_for_pool: Optional[float] = None,
    ) -> SelectionResult:
        """
        Main entrypoint for ML gate.

        Parameters
        ----------
        population:
            DB-miss candidates only.
        n_exploit:
            Number of best candidates by surrogate score.
        n_explore:
            Number of most uncertain candidates.
        feasibility_filter:
            If True, only candidates with ok_pred == 1 enter selection pool.
        min_p_ok_for_pool:
            Optional probability threshold for selection pool, e.g. 0.3 or 0.5.
            Applied in addition to feasibility_filter if provided.

        Returns
        -------
        SelectionResult
            - prediction_df: all DB-miss candidates with ML outputs
            - selected_df: all selected candidates for physics
            - exploit_df: top by surrogate score
            - explore_df: top by uncertainty
            - non_selected_df: remaining DB-miss candidates
        """
        bundle = self.predict_population(population)
        prediction_df = self._build_prediction_df(bundle)

        pool = prediction_df.copy()

        if feasibility_filter:
            pool = pool[pool["ok_pred"] == 1].copy()

        if min_p_ok_for_pool is not None:
            pool = pool[pool["p_ok"] >= float(min_p_ok_for_pool)].copy()

        if len(pool) == 0:
            # Fallback: if filtering is too strict, use all DB-miss
            pool = prediction_df.copy()

        # Exploitation: smaller surrogate_score is better
        exploit_n = min(n_exploit, len(pool))
        exploit_df = pool.nsmallest(exploit_n, "surrogate_score").copy()
        exploit_df["selected_for_physics"] = True
        exploit_df["selection_type"] = "exploit"

        # Exploration: highest uncertainty, excluding already selected exploit samples
        remain = pool.drop(index=exploit_df.index, errors="ignore")
        explore_n = min(n_explore, len(remain))
        explore_df = remain.nlargest(explore_n, "total_uncertainty").copy()
        explore_df["selected_for_physics"] = True
        explore_df["selection_type"] = "explore"

        # Combine selected
        selected_df = pd.concat([exploit_df, explore_df], axis=0)
        selected_df = selected_df.loc[~selected_df.index.duplicated()].copy()

        # Mark selected in full prediction table
        prediction_df.loc[selected_df.index, "selected_for_physics"] = True
        prediction_df.loc[exploit_df.index, "selection_type"] = "exploit"
        prediction_df.loc[explore_df.index, "selection_type"] = "explore"

        # Non-selected DB-miss remain ML-based
        non_selected_df = prediction_df.loc[~prediction_df.index.isin(selected_df.index)].copy()

        return SelectionResult(
            prediction_df=prediction_df,
            selected_df=selected_df,
            exploit_df=exploit_df,
            explore_df=explore_df,
            non_selected_df=non_selected_df,
        )